name: Deploy to Spaceship

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ${{ secrets.FTP_REMOTE_PATH }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.github*
            **/.github*/**
            **/workflows/**
            **/README.md
            **/LICENSE
            **/package.json
            **/package-lock.json
            **/.gitignore
            **/.editorconfig
            **/*.log
            **/.env
            **/.env.*
